### PR TITLE
Fix empty argument error for find command

### LINKED ISSUE #181: [PE-D][Tester F] No error message when field after prefix is empty for Find Command
Maybe a error message can be shown to prompt the user to fill in something.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yongkotaro/ped#2

### PR DESCRIPTION
**Pull request by matthewken19**
Fix #181

### CODE REVIEW

**Review by marclamp — COMMENTED** [review]
LGTM, did you update/add the relevant test cases in `FindCommandParserTest.java` ?

File: src/main/java/educonnect/logic/parser/FindCommandParser.java [hunk 1]
```diff
@@ -48,18 +50,35 @@ public FindCommand parse(String args) throws ParseException {
...
+            predicates.add(new EmailContainsKeywordsPredicate(email));
+        }
+        if (argMultimap.getValue(PREFIX_TELEGRAM_HANDLE).isPresent()) {
+            String telegramHandle = argMultimap.getValue(PREFIX_TELEGRAM_HANDLE).get().trim();
+            if (telegramHandle.isEmpty()) {
+                throw new ParseException(
+                        String.format(MESSAGE_EMPTY_PREFIX_ARGUMENT, "TELEGRAM_HANDLE", "TELEGRAM_HANDLE"));
+            }
+            predicates.add(new TelegramContainsKeywordsPredicate(telegramHandle));
+        }
```
Comment (fy17ohhh) [inline src/main/java/educonnect/logic/parser/FindCommandParser.java:81]: - could consider adding parameters as static variables to avoid using magic literals
- possible implementation of SLAP here to improve code quality

Comment (matthewken19) [reply src/main/java/educonnect/logic/parser/FindCommandParser.java]: Thanks for the input! I abstract out the error messages to the message class.

**Review by marclamp — COMMENTED** [review]
LGTM
