### PR TITLE
Fix first day not captured for timetable-related commands

### LINKED ISSUE #137: Bug with Add/Edit Command
Sometimes the add/edit command for the timetable portion does not capture the first `Day` prefix.

i.e. for `edit 3 c/mon: 10-12, 12-14 tue: 13-15, 17-18, wed: 11-14`, the `Period`s for Monday is not captured.

* The issue lies in argMultimap, where:
  * When creating the argMultimap, the number of `Prefix` is correct
  * But the first one creates an empty one (`""`) instead of `"mon:"`

### PR DESCRIPTION
**Pull request by marclamp**
Resolves #137

### CODE REVIEW

File: src/main/java/educonnect/logic/parser/AddCommandParser.java [hunk 1]
```diff
@@ -84,8 +84,9 @@ public AddCommand parse(String args) throws ParseException {
      */
     public static ArrayList<String> tokenizeForTimetable(String fullTimetableString) {
         ArgumentMultimap argMultimap =
-                ArgumentTokenizer.tokenize(fullTimetableString, PREFIX_TIMETABLE_MONDAY, PREFIX_TIMETABLE_TUESDAY,
-                        PREFIX_TIMETABLE_WEDNESDAY, PREFIX_TIMETABLE_THURSDAY, PREFIX_TIMETABLE_FRIDAY,
+                ArgumentTokenizer.tokenize(" " + fullTimetableString.toLowerCase(), PREFIX_TIMETABLE_MONDAY,
```
Comment (fy17ohhh) [inline src/main/java/educonnect/logic/parser/AddCommandParser.java:87]: LGTM, nice idea to add in the space to resolve the bug and also making it case insensitive:)

**Review by fy17ohhh — APPROVED** [review]

**Comment by darryl-chan** [comment]
LGTM
