### PR TITLE
Fix edit command unique identifier bug

### LINKED ISSUE #180: [PE-D][Tester E] Edit person with student number
No one has a student number of 1, although it states there exists one in the address book.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: sarjinius/ped#2

### PR DESCRIPTION
**Pull request by matthewken19**
Fix #180 
- Add predicates for exact matching
- Update test files

### CODE REVIEW

File: src/test/java/educonnect/logic/parser/EditCommandParserTest.java [hunk 1]
```diff
@@ -83,43 +83,59 @@ public void parse_missingParts_failure() {
...
+        assertParseFailure(parser, EDIT_ID_PREFIX_INDEX + "1" + INVALID_STUDENT_ID_DESC,
+                StudentId.MESSAGE_CONSTRAINTS);
+        // invalid email
+        assertParseFailure(parser, EDIT_ID_PREFIX_STUDENT_ID + VALID_STUDENT_ID_AMY + INVALID_EMAIL_DESC,
+                Email.MESSAGE_CONSTRAINTS);
+        // invalid telegram handle
+        assertParseFailure(parser, EDIT_ID_PREFIX_EMAIL + VALID_EMAIL_AMY + INVALID_TELEGRAM_HANDLE_DESC,
+                TelegramHandle.MESSAGE_CONSTRAINTS);
+        // invalid tag
+        assertParseFailure(parser, EDIT_ID_PREFIX_INDEX + "1" + INVALID_TAG_DESC, Tag.MESSAGE_CONSTRAINTS);
```
Comment (jeremiahlzz) [inline src/test/java/educonnect/logic/parser/EditCommandParserTest.java:122]: Thanks for tidying up the test cases.

**Review by jeremiahlzz — APPROVED** [review]
LGTM

**Review by marclamp — COMMENTED** [review]
Looks good :)
